### ISSUE TITLE
add policy gui to make it easier to create policies for auth

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/casa#10]
For instance, if the user is accessing under certain circumstances, e.g. `device = mobile` or `ip_address = fromIndia`, prompt for `super_gluu_push` authentication. . 

We should maybe evaluate AWS IAM policy GUI for ideas: 

https://aws.amazon.com/blogs/security/use-the-new-visual-editor-to-create-and-modify-your-aws-iam-policies/

This would be a nice enterprise feature.

**Comment by nynymike** [comment]
Other solutions are taking precedence.
