### ISSUE TITLE
Remove prompt about a commercial license in installer

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/casa#108]
Casa is free open source software now...

![nocommercial](https://user-images.githubusercontent.com/5444180/71533252-c3fc9480-28c5-11ea-9d9e-f49d2ab08d6f.png)

**Comment by mbaser** [comment]
In my opinion even it is open source we must present a license. For example:
```
Do you acknowledge that use of the Gluu Casa is under the Apache  License V2?
```
@jgomer2001 @willow9886 What do you think?

**Comment by mbaser** [comment]
Changed to Apache V2
![Screenshot_2019-12-29_20-25-51](https://user-images.githubusercontent.com/6398752/71560333-ad973a00-2a79-11ea-9386-fc852703ce62.png)

**Comment by willow9886** [comment]
@mbaser yes, looks good. Thanks.
