### ISSUE TITLE
Add auditing capabilities

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/casa#11]
In the near feature, we should log login attempts. Of special attention those under the circumstances listed in [#30](https://github.com/GluuFederation/cred-manager/issues/30):

*  When IP address unrecognized
* When the device is unrecognized

We may also add e-mail notifications to users when these "suspicious" logins occur

The admin needs to be able to use this information (searches, reports...)

**Comment by nynymike** [comment]
This is not the right place to implement this capability
