### ISSUE TITLE
Remove usage of deprecated classes in Inwebo plugin

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/casa#111]
`org.gluu.casa.plugins.inwebo.InweboService` uses several deprecated classes. It uses the old API which has no support for couchbase. Please update

**Comment by jgomer2001** [comment]
@maduvena Deprecated classes were removed by
https://github.com/GluuFederation/casa/commit/a3daab2a11e12068ab2b89754522a8cecdfaaf8a

Plugin won't compile anymore. Needs attention.

**Comment by maduvena** [comment]
[15f0550](https://github.com/GluuFederation/casa/commit/15f05507e0bb74c333c94915b78e024464bb5f9e
)
