### ISSUE TITLE
Add Plugin for Browser Cert authentication.

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/casa#112]
X.509 cert authentication is an important, standards based authentication mechanism, used widely by governments and enteprise customers around the world.

Replaces https://github.com/GluuFederation/casa/issues/91

**Comment by jgomer2001** [comment]
@nynymike  I would like to better understand the role of casa here, ie. how would the end-user experience be for enrollment?

According to https://gluu.org/docs/ce/4.1/authn-guide/cert-auth/prerequisites the user is supposed to present his card to some hardware that adds the card's certificate to the browser

Also I see there is no de-facto way to bridge smart cards with browsers. It's a fragmented ecosystem

Is this issue just about authentication (ie. adding cert authn as one of the possible paths in casa flow) ?

**Comment by nynymike** [comment]
I think the answer is yes...
