### ISSUE TITLE
Casa Plugin for user registration

### ISSUE THREAD

**Issue by maduvena** [GluuFederation/casa#117]
1. Build a public facing page which allows a person to register himself
2. The admin should be able to customize the look and feel, registration fields, and also ideally there should be an interception script that enables the admin to notify other applications about the registrations.
3. These end-users may have a smart card (i.e. an X.509 certificate).
An X.509 certificate may have attributes.
We may want to gather those attributes, and enter them automatically for the user (and not let the user change them).

**Comment by jgomer2001** [comment]
Outsourced
