### ISSUE TITLE
Make adjustments needed wrt oxd 3.1.4 not allowing to set expiration time

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/casa#15]
Upon start, casa creates client (if not existent). Then updates client to extend life time. The same is done when supplying a different oxd server in admin UI

oxd 3.1.4 does not handle expiration time anymore, accommodate.

**Comment by jgomer2001** [comment]
Updated client registration cust script 
https://github.com/GluuFederation/community-edition-setup/commit/4e1d0083460bf6c0d7cb96ca35e7ed3d39fc95ab

**Comment by jgomer2001** [comment]
@afroDC , for installer we have to modify `oxScript` attribute of script with DN `inum=%(inumOrg)s!0011!DAA9.F7F8,ou=scripts,o=%(inumOrg)s,o=gluu` 

you can assume the file is found at `/opt/dist/gluu/casa.py`

**Comment by afroDC** [comment]
The script now assumes the Casa client registration script will be unpacked by the gluu-casa-3.1.4 package to `/opt/dist/gluu/casa_client_reg.py`

https://github.com/GluuFederation/post-installation-setup/commit/c7e0f34ed9a5066330a14f206ef92a3141adff36
