### ISSUE TITLE
Create uninstaller for casa

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/casa#20]
Upon package uninstallation, we should remove certain things, I'll add here what I consider relevant

**Comment by afroDC** [comment]
@jgomer2001 is the intention to uninstall Casa with an `apt-get uninstall gluu-casa-3.1.4` command? I'm not sure some of the LDAP tasks can be handled with the package manager in Ubuntu and RHEL. We may need a clean-up script to do those other LDAP related tasks.

**Comment by afroDC** [comment]
https://github.com/GluuFederation/post-installation-setup/blob/version_3.1.4/casa_cleanup.py

For testing.

**Comment by jgomer2001** [comment]
@afroDC a couple of comments

--
In `delCustomScripts` of casa_cleanup, it seems script is deleted by using `displayName` attribute, unfortunately we have two scrips named "client_registration":

https://github.com/GluuFederation/community-edition-setup/blob/version_3.1.4/templates/scripts.ldif#L433

I opened an [issue](https://github.com/GluuFederation/community-edition-setup/issues/496) milestoned 3.1.5. Meanwhile we need to add some extra logic to delete the right client reg script, there are some clues at the top of this issue 

--

For `delCasaFiles`, I think it's safer to stop casa service beforehand

--

For `restartOxauth`. Sorry for the misunderstanding, but I wrote 

> restart oxauth?

because I'm not sure if we need this step. Meanwhile, let's remove the prompt only

**Comment by afroDC** [comment]
> I opened an issue milestoned 3.1.5. Meanwhile we need to add some extra logic to delete the right client reg script, there are some clues at the top of this issue

In the script I'll change the parameter to something like this:

```
    # To be more explicit while searching for the scripts and
    # because the script inums are static, we will search for the
    # actual inum for each item, and delete them accordingly.

    scriptNames = [
            '!0011!BABA.CACA',
            '!0011!DAA9.F7F8'
            ]

    for script in scriptNames:
        
        conn.search(search_base = 'inum={0}{1},ou=scripts,o={0},o=gluu'.format(oInum,script),
        search_filter = '(objectClass=*)',
        search_scope = SUBTREE,
        attributes='displayName')
```

**Comment by afroDC** [comment]
> For restartOxauth. Sorry for the misunderstanding, but I wrote

> restart oxauth?

> because I'm not sure if we need this step. Meanwhile, let's remove the prompt only

I don't think a service restart is needed. I doubt there would be any conflicts with oxAuth while running, besides having some libraries loaded into memory that aren't being used anymore. So remove the prompt and do it anyway?

**Comment by afroDC** [comment]
> For delCasaFiles, I think it's safer to stop casa service beforehand

I'll add a call to stop Casa first.

**Comment by afroDC** [comment]
https://github.com/GluuFederation/post-installation-setup/commit/8c5f499b507412f5428a2f14b4f35890b632a477

**Comment by jgomer2001** [comment]
@afroDC installer is good,  I  have these minor observations:

routine `makeDirs`
we don't need to create dir /opt/gluu/jetty/oxauth/custom/pages/casa

--

update script to point to this war: 
`https://ox.gluu.org/maven/org/xdi/casa/3.1.4.Final/casa-3.1.4.Final.war`

--

![link_license](https://user-images.githubusercontent.com/5444180/48970450-44bdd280-efda-11e8-8b85-c9d0f63d6a1d.png)

can we include a link to
https://github.com/GluuFederation/casa/raw/master/LICENSE.md

--

![oxd_3 1 4_explicit](https://user-images.githubusercontent.com/5444180/48970460-599a6600-efda-11e8-8d8a-c487324e94bc.png)

I don't think casa will work well with any version of oxd, can you make it explicit that 3.1.4 is needed?

--

![agree_t](https://user-images.githubusercontent.com/5444180/48970468-72a31700-efda-11e8-8601-bb5af6aa7d08.png)

I hit `t`, and It assumed `Y` !

**Comment by jgomer2001** [comment]
@natt-tester found the following when running the cleaning script in RHEL6:

```
GLUU.[root@rhelce6 community-edition-setup]# ./casa_cleanup.py
Gathering LDAP Server Properties..
Decoding bindPassword..

Traceback (most recent call last):
  File "./casa_cleanup.py", line 109, in <module>
    conn = bindLDAP()
  File "./casa_cleanup.py", line 96, in bindLDAP
    ldap_uri = "ldaps://{}".format(host)
ValueError: zero length field name in format
```

Python version here is 2.6.6

From my understanding of this doc [page](https://docs.python.org/2/library/string.html#format-string-syntax),  only starting with 2.7 you can omit the position numbers when using `format`?

**Comment by jgomer2001** [comment]
@afroDC It seems most gluu servers  come with python 2.7.x ...

**Comment by afroDC** [comment]
I'm usually good about this. Here's the fix https://github.com/GluuFederation/post-installation-setup/commit/606318dc4700806eb8be36733e45da939376b2a4

**Comment by jgomer2001** [comment]
works like a charm
