### ISSUE TITLE
Casa Plugin query 

### ISSUE THREAD

**Issue by mihir2780** [GluuFederation/casa#207]
Hello,
We need to integrate Thales (earlier Gemalto) SafeNet as MFA app with Gluu. Does a plugin for this already exists? If not, please point us to the documentation to refer to get the plugin for Thales SafeNet developed. We intend to use it as a MFA through Casa.

**Comment by Cookedjc** [comment]
hi @mihir2780   thanks for asking.  We don't have a plugin for Gemalto but you should be able to get it to work. We have a DUO plugin example that is pretty close.  Check out this guide https://gluu.org/docs/casa/4.2/developer/intro-plugin/#introduction-to-plugin-development
Also check out the DUO plugin https://github.com/GluuFederation/docs-casa-prod/wiki/DUO-plugin
If you need help with this and your project can spare a little budget we can refer you to a partner who can help you.

**Comment by mihir2780** [comment]
Hello @Cookedjc ,
Thank you for your assistance.
I will let you know if further assistance is required in future for this plugin.

Thanks and regards,
Mihir Bhusawalkar

**Comment by mihir2780** [comment]
Hello @Cookedjc ,

I am using gluu version 4.3.1. on VMware (Ubuntu 20.X)
I have followed this URL( https://github.com/GluuFederation/docs-casa-prod/wiki/DUO-plugin).
I am facing a problem where I am not able to register duodevice on the casa portal. Once I try to register a duo device as admin or a user, it does not register the device on the casa portal. 
Please note that I have uploaded duo plugin(4.3.1 version) on casa portal and duo script is used as it is which is provided by default on gluu server. I have attached casa logs for better understanding.(As soon as I click on DUO credentials in 2FA section, I get error mentioned in the logs)
Any type of assistance is appreciated on the above problem.
![casa logs](https://user-images.githubusercontent.com/64555810/170693654-1c69ca99-5f34-40c4-9851-5ff09784482b.JPG)


Thanks and Regards,
Mihir Bhusawalkar

**Comment by Cookedjc** [comment]
Hi Mihir  - you will need to configure DUO service from CISCO https://duo.com/docs/getting-started to test the plugin as it is today. DUO is an authentication service much like Gemalto. I introduced it so that your could review the plugin code and model a Gemalto Plugin the same way.  We have not attempted Gemalto before. Our technical support team may be able to help you get it working once you get down to final troubleshooting. We don't support Gemalto today as a plugin but would consider adding it to the available plugins for CASA one day as part of our support contract.

**Comment by nynymike** [comment]
Mihir, you need to get an account on support.gluu.org. Github issues are for bugs or enhancements, not support.

**Comment by mihir2780** [comment]
> Hi Mihir - you will need to configure DUO service from CISCO https://duo.com/docs/getting-started to test the plugin as it is today. DUO is an authentication service much like Gemalto. I introduced it so that your could review the plugin code and model a Gemalto Plugin the same way. We have not attempted Gemalto before. Our technical support team may be able to help you get it working once you get down to final troubleshooting. We don't support Gemalto today as a plugin but would consider adding it to the available plugins for CASA one day as part of our support contract.

Hello @Cookedjc ,
I was trying to implement DUO plugin with gluu casa for my better understanding about how plugin works in casa. I followed exact all same steps and still I was getting error which I mentioned above. I was trying to implement the DUO plugin as a usecase in this scenario for gluu casa.

Regards,
Mihir

**Comment by mihir2780** [comment]
> Mihir, you need to get an account on support.gluu.org. Github issues are for bugs or enhancements, not support.

Hello Mike,
Thank you for your advice, I have an account on the support.gluu.org.

Regards,
Mihir
