### ISSUE TITLE
Prompt to accept license during installation

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/casa#21]
Add prompt to accept or deny license during package installation.  If denied, installation should stop.

**Comment by afroDC** [comment]
https://github.com/GluuFederation/post-installation-setup/commit/6b330c3879c0196883b6d96343fd29239d1fb384#diff-794364e4b660ba3c3d666600cd8d02c1

Perhaps more text from the license should be added in a paragraph before the prompt for accepting is displayed.

**Comment by willow9886** [comment]
What about... 

> Do you acknowledge that Casa is commercial software, and use of Casa is only permitted under the Gluu License Agreement for Gluu Casa

**Comment by afroDC** [comment]
https://github.com/GluuFederation/post-installation-setup/commit/24a5bb01a6aaef6a2f02b3ac04a233cdff17293c
