### ISSUE TITLE
Enable unlimited cryptography

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/casa#22]
We have to configure JDK for unlimited crypto, 

There is a file in /opt/jre/lib/security called java.security
We have to _uncomment_ this line in the file:

```
#crypto.policy=unlimited
```

account /opt/jre is a link to actual JRE whose location may vary among Gluu versions, for instance, it could be `/opt/jdk1.8.0_181/jre/` in the case of 3.1.4

We can apply this step in the installer at any moment before casa service starts.

related https://github.com/GluuFederation/community-edition-setup/issues/495

**Comment by jgomer2001** [comment]
Actually, this wouldn't be required in case the Gluu server was installed including oracle JCE, but how to know?

**Comment by afroDC** [comment]
> Actually, this wouldn't be required in case the Gluu server was installed including oracle JCE, but how to know?

https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L1280

According to this we could just check if there exists either `US_export_policy.jar` or `local_policy.jar` in `/opt/jre/jre/lib/security`.

**Comment by afroDC** [comment]
> > Actually, this wouldn't be required in case the Gluu server was installed including oracle JCE, but how to know?
> 
> https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L1280
> 
> According to this we could just check if there exists either `US_export_policy.jar` or `local_policy.jar` in `/opt/jre/jre/lib/security`.

This however has nothing to do with `crypto.policy=unlimited`. Perhaps we still need to change it.

**Comment by jgomer2001** [comment]
>According to this we could just check if there exists either US_export_policy.jar or local_policy.jar in /opt/jre/jre/lib/security.

A standard java installation comes with these two files, JCE files are simply different with exact names

**Comment by afroDC** [comment]
Could we hash the JCE version and check that against whatever file is in `/opt/jre/jre/lib/security/`?

**Comment by jgomer2001** [comment]
I think one way could be like this:
both local_policy and US_export_policy jar files have a manifest file inside. You can extract them by using `jar -xf file.jar META-INF/MANIFEST.MF`

A java installation with limited crypto has a line like
```Crypto-Strength: limited``` 

while if having the JCE jars, they have

```Crypto-Strength: unlimited```

**Comment by jgomer2001** [comment]
no, when negative you just have to do

>There is a file in /opt/jre/lib/security called java.security
>We have to uncomment this line in the file:

>#crypto.policy=unlimited

because with the JDK bundled in current Gluu, there is no need to install anything, see https://github.com/GluuFederation/community-edition-setup/issues/495

**Comment by afroDC** [comment]
https://github.com/GluuFederation/post-installation-setup/commit/c7e0f34ed9a5066330a14f206ef92a3141adff36
