### ISSUE TITLE
Clearer names for button colors in  Custom Branding plugin

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/casa#23]
![image](https://user-images.githubusercontent.com/36208047/49021854-321dd780-f159-11e8-8406-f5303302cbdd.png)

The names for the button categories in the Custom Branding plugin for Casa are confusing and non-intuitive.  As it stands, they are as follows:

- Primary: buttons that trigger an action (such as saving, updating, etc)
- Secondary: Miscellaneous buttons that don't fit the other two categories
- Tertiary: Undo, close, or cancel

With the current names, there's an implied hierarchy of importance that isn't met. At the very least, Secondary and Tertiary button names should be flipped so that the least important is the miscellaneous catch-all. It would be nice to give more descriptive titles, though.

**Comment by jgomer2001** [comment]
Please suggestions @willow9886 and @shmorri

**Comment by shmorri** [comment]
Perhaps:
Primary
Cancel
Misc
