### ISSUE TITLE
ldap_persist_exception in casa.log

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/casa#25]
Setup: **Gluu Server 3.1.4 + casa 3.1.4 + oxd in a RHEL6 vm**

All the components are up and running, OTP custom script enabled in oxtrust, but when I try to enroll a soft token for my admin in casa, all the valid codes entered get an error message: "Wrong or empty code entered". There are errors in the logs:
[ldap_persist_exception.txt](https://github.com/GluuFederation/casa/files/2642491/ldap_persist_exception.txt)
Did I miss something?

**Comment by natt-tester** [comment]
@jgomer2001 -- the date was indeed one day short, my bad! OTP enrollment works fine now. 
About the SuperGluu errors: I've changed the log level and will try to catch this behavior, but so far with no success. I'll keep you posted on it.

**Comment by jgomer2001** [comment]
I'm closing, this message may arise when there is no user fido branch yet and the app tries to read user's fido devices. Upon enrollment, oxauth creates that branch, after that queries succeed
