### ISSUE TITLE
Email2FA is not working in CASA

### ISSUE THREAD

**Issue by mzico** [GluuFederation/casa#255]
- Installed email2FA plugin in CASA
- Enabled email2FA authentication script from oxAuth
- CASA not loading email2FA as "available 2FA" 
- Gluu Server 4.5

Screenshots attached. 
![Screenshot from 2023-02-17 06-59-35](https://user-images.githubusercontent.com/7156097/219528055-a982457c-6d9d-4b02-bbda-e4447c4858f0.png)

![Screenshot from 2023-02-17 07-00-37](https://user-images.githubusercontent.com/7156097/219528029-73e25ed0-8ecf-4f53-8746-df7c9dfa33e8.png)

![Screenshot from 2023-02-17 06-59-44](https://user-images.githubusercontent.com/7156097/219528044-54c56e02-31e8-44f1-949e-ffbf100bbbd1.png)

**Comment by smansoft** [comment]
The root of the problem, described in the bug: wrong name of  the auth method.
**email_2fa_core** should be used.
![image](https://user-images.githubusercontent.com/8136531/225893278-8bd2527e-b805-40d7-b1ef-98c74c616c7a.png)
In this case:
![image](https://user-images.githubusercontent.com/8136531/225893610-46c53fc1-ad8d-4241-807a-d27586a74631.png)
I.e. auth method is enabled.
Please use this script:
https://github.com/GluuFederation/casa/tree/master/plugins/email_2fa_core/extras
with the plug-in:
https://github.com/GluuFederation/casa/tree/master/plugins/email_2fa_core
.

**Comment by smansoft** [comment]
One more screenshot - loaded plug-in:
![image](https://user-images.githubusercontent.com/8136531/225894766-c66104a4-54bf-4aa4-a7e5-42629b88aa1e.png)
