### ISSUE TITLE
Unable to find the email2fa to enable under casa "Enabled authentication methods

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/casa#283]
**Describe the bug**
Unable to find the email2fa to enable under casa "Enabled authentication methods.

***To Reproduce**
1. Enabled email2fa in person authentication script.
2. Downloaded all the files and script to the suggested folders.
3. Downloaded and uploaded casa plugin email_2fa_core-4.5.4.Final-jar-with-dependencies.jar
4. Restarted casa service

**Expected behavior**
email2fa should be show in casa enable auth method

**Screenshots**
there is no method available

**Desktop (please complete the following information):**
  - gluu 4.5.3

**Comment by jgomer2001** [comment]
I followed the instructions in https://gluu.org/docs/casa/4.5/plugins/email2fa/ and got:

![Screenshot from 2024-07-05 14-12-01](https://github.com/GluuFederation/casa/assets/5444180/e5c96804-f983-4ec9-9d07-18b521801e82)

![Screenshot from 2024-07-05 14-13-45](https://github.com/GluuFederation/casa/assets/5444180/210a9618-83fd-4f59-a118-7eb6e03d6eca)
