### ISSUE TITLE
fix(casa):unable to launch casa

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/casa#291]
unable to launch casa

env:
suse 15 sp5
DB- opendj
gluu 4.5.5.final

log:

[casa.log.zip](https://github.com/user-attachments/files/16453881/casa.log.zip)
[oxauthlog.zip](https://github.com/user-attachments/files/16453911/oxauthlog.zip)
[2024_08_01.jetty.log](https://github.com/user-attachments/files/16455115/2024_08_01.jetty.log)
[casa.log](https://github.com/user-attachments/files/16455116/casa.log)
[casa_async_jobs.log](https://github.com/user-attachments/files/16455118/casa_async_jobs.log)

**Comment by jgomer2001** [comment]
unable to reproduce
