### ISSUE TITLE
Deleting record in oxTrust should delete in Casa UI

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/casa#31]
When an Gluu admin deletes an enrolled device from a user record, the device should also be removed from the user's Casa UI. Currently it creates an unnamed entry in Casa, as seen in screenshot below. 

![image](https://user-images.githubusercontent.com/5271048/51836813-1fde2800-22c7-11e9-82a4-543302d5d472.png)

**Comment by jgomer2001** [comment]
This was due to oxTrust doing partial delete of data. With latest oxtrust fixes this is solved.
