### ISSUE TITLE
Logout inconsistency between /identity and /casa

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/casa#32]
# Observation

Login out of Gluu server Admin Ui don't log out of Casa.

# Steps to reproduce

- Launch a new incognito browser
- Log into **dc.gluu.org**
- The  visit   **dc.gluu.org/casa** on another tab
- Back in oxtrust Admin Ui and logout
- Back to casa tab and hit refresh

## Expected
 You should be redirect to login page
## Actual
  Everything is working.

# Next step
Try to log out of casa, you will receive this message:
**{"error":"invalid_grant_and_session","error_description":"The provided access token and session state are invalid or were issued to another client.","reason":"Failed to identify session by session_id query parameter or by session_id cookie."}**
# Screenshots
![image](https://user-images.githubusercontent.com/7513418/51895241-fa761a80-23a9-11e9-8e36-75d78ab9f8b2.png)

**Comment by jgomer2001** [comment]
duplicated https://github.com/GluuFederation/oxAuth/issues/992
