### ISSUE TITLE
REST API for usage metrics

### ISSUE THREAD

**Issue by maduvena** [GluuFederation/casa#66]
Currently, Casa checks usage data (usage metrics) from the internal LDAP and adds it to an encrypted text file
and then if / when we request the file, we can see average monthly volume of usage
We need to turn this into a REST API call which anyone (Gluu / customers) can use to determine usage (for billing purposes)

from technical perspective all the logic is concentrated in this single file:
https://github.com/GluuFederation/casa/blob/master/app/src/main/java/org/gluu/casa/timer/StatisticsTimer.java
it’s coded with no comments, and it’s obscure

The rest service you are building, will read those files depending on parameters supplied and give output accordingly

code the service first (public access), then we add the security to it

in casa we already have a couple of coded services for you to follow:
Here are the services implemented
https://github.com/GluuFederation/casa/tree/master/app/src/main/java/org/gluu/casa/plugins/authnmethod/rs

and the client which uses it:
https://github.com/GluuFederation/casa/tree/master/extras/enrollment-client

**Comment by jgomer2001** [comment]
See #224
