### ISSUE TITLE
Create swagger file for usage metrics REST API 

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/casa#73]
Related #66 

We usually document APIs using swagger. Create a yaml for metrics API, example: https://github.com/GluuFederation/casa/blob/master/app/src/main/webapp/enrollment-api.yaml

That way anyone can easily automate the creation of a client that consumes such service

**Comment by nynymike** [comment]
We need to add this swagger doc link to the docs.

**Comment by jgomer2001** [comment]
See #224
