### ISSUE TITLE
Setting up a proxy in casa

### ISSUE THREAD

**Issue by maduvena** [GluuFederation/casa#74]
Some customers of Gluu + casa may require a proxy to be setup because their policies wont allow direct connections to the internet 
[https://support.gluu.org/access-management/7386/sending-sms-not-possible/](url)

**Comment by nynymike** [comment]
I don't think this is a feature for Casa. Really, the interception script would need to support a proxy. This could of course always be added by the customer, or we could do it when there is demand.
