### ISSUE TITLE
Exception - "Object not an instance of declaring class" is raised for model classes defined in plugin 

### ISSUE THREAD

**Issue by maduvena** [GluuFederation/casa#97]
1. raised when a plugin is re-loaded
2. Is not raised when the model classes has been defined in casa-shared 
3. Raised when model class is inherited from model class in casa-shared
4. Happens in the oxcore-persistence API when method.invoke (target) is called 
5. The reason for the defect is - the class loader for "Method" and the classloader for "target" are different. The plugin should have a single classloader (the class loader of the re-loaded plugin)

**Comment by jgomer2001** [comment]
Problem seems to have disappeared in 4.2 :)
